#!/usr/bin/env bash
# Numbra — launch Claude Code as the critical reviewer for a phase.
#
# Usage:  scripts/review.sh <milestone>      e.g.  scripts/review.sh M0
#         (normally run by scripts/autopilot.sh, which first saves the test run as
#          reviews/<M>/CHECK-<n>.log; you can also run it by hand)
#
# What it does:
#   1. Checks reviews/<milestone>/HANDOFF.md exists.
#   2. Works out the next review number n (REVIEW-1, REVIEW-2, ...).
#   3. Runs Claude Code headless (-p) with the reviewer prompt, READ-ONLY tools
#      plus web search, so the reviewer can read and verify but never edit the repo.
#   4. Writes Claude's review to reviews/<milestone>/REVIEW-<n>.md and prints the verdict.
#
# Exit codes: 0 = PASS, 10 = PASS WITH CHANGES, 20 = REVISE,
#             30 = round limit reached (autopilot closes the milestone and records the
#                  unresolved dissent for humans), 1 = error.
#
# Requirements: Claude Code CLI installed and signed in (`claude auth status`),
# network access for this command. Optional env vars:
#   NUMBRA_REVIEW_MODEL       model alias, default: opus
#   NUMBRA_REVIEW_MAX_ROUNDS  default: 3
#   NUMBRA_REVIEW_BUDGET_USD  per-review spend cap (API-key billing only), default: unset

set -euo pipefail

PHASE="${1:?usage: scripts/review.sh <milestone>  (e.g. M0)}"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

DIR="reviews/${PHASE}"
PROMPT="prompts/claude-reviewer.md"
MODEL="${NUMBRA_REVIEW_MODEL:-opus}"
MAX_ROUNDS="${NUMBRA_REVIEW_MAX_ROUNDS:-3}"

command -v claude >/dev/null || { echo "ERROR: claude CLI not found on PATH" >&2; exit 1; }
[[ -f "$DIR/HANDOFF.md" ]] || { echo "ERROR: $DIR/HANDOFF.md not found — Builder must write it first" >&2; exit 1; }
[[ -f "$PROMPT" ]] || { echo "ERROR: $PROMPT not found" >&2; exit 1; }

# Next review number.
n=1
while [[ -f "$DIR/REVIEW-$n.md" ]]; do n=$((n + 1)); done

if (( n > MAX_ROUNDS )); then
  echo "ROUND LIMIT: $MAX_ROUNDS reviews already done for $PHASE." >&2
  exit 30
fi

# A round after the first must have a Builder response to the previous review.
if (( n > 1 )) && [[ ! -f "$DIR/RESPONSE-$((n - 1)).md" ]]; then
  echo "ERROR: $DIR/RESPONSE-$((n - 1)).md missing — answer REVIEW-$((n - 1)) before requesting another review" >&2
  exit 1
fi

OUT="$DIR/REVIEW-$n.md"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

TASK="Review milestone '${PHASE}'. This is review round ${n} of at most ${MAX_ROUNDS}.
Start with docs/ROADMAP.md (the acceptance tests for ${PHASE}), AGENTS.md if present, and
${DIR}/HANDOFF.md, then read every file the handoff references, including code and tests."
if [[ -f "$DIR/CHECK-$n.log" ]]; then
  TASK+="
The harness ran scripts/check.sh independently; its output is ${DIR}/CHECK-${n}.log.
Trust that log over any test claims in HANDOFF, and treat a FAIL there as blocking."
fi
if (( n > 1 )); then
  TASK+="
Also read the earlier rounds in ${DIR}/ (REVIEW-*.md and RESPONSE-*.md). Check each earlier
blocking issue: say whether it is resolved, and judge any 'reject' answers on their merits."
fi
TASK+="
Output ONLY the review in Markdown, starting with the line 'Verdict: <PASS|PASS WITH CHANGES|REVISE>'."

EXTRA=()
[[ -n "${NUMBRA_REVIEW_BUDGET_USD:-}" ]] && EXTRA+=(--max-budget-usd "$NUMBRA_REVIEW_BUDGET_USD")

echo "Running Claude reviewer (round $n, model $MODEL)…" >&2

# Read-only toolset: the reviewer can read, search and verify on the web, but has no
# Bash, Write or Edit, so it cannot change the repo. The script writes the file.
claude -p "$TASK" \
  --model "$MODEL" \
  --append-system-prompt-file "$PROMPT" \
  --tools "Read,Glob,Grep,WebSearch,WebFetch" \
  --allowedTools "Read" "Glob" "Grep" "WebSearch" "WebFetch" \
  --permission-prompts none \
  --max-turns 60 \
  --output-format text \
  --no-session-persistence \
  ${EXTRA[@]+"${EXTRA[@]}"} > "$TMP"

[[ -s "$TMP" ]] || { echo "ERROR: reviewer produced no output" >&2; exit 1; }

{
  echo "<!-- Generated by scripts/review.sh — Claude reviewer, round $n, $(date -u +%Y-%m-%dT%H:%MZ), model $MODEL -->"
  echo
  cat "$TMP"
} > "$OUT"

VERDICT="$(grep -m1 -oiE 'Verdict:[[:space:]]*\**[[:space:]]*(PASS WITH CHANGES|PASS|REVISE)' "$OUT" \
  | sed -E 's/.*Verdict:[[:space:]]*\**[[:space:]]*//I' | tr '[:lower:]' '[:upper:]' || true)"

echo "Wrote $OUT"
echo "VERDICT: ${VERDICT:-UNKNOWN}"

case "$VERDICT" in
  "PASS")              exit 0 ;;
  "PASS WITH CHANGES") exit 10 ;;
  "REVISE")            exit 20 ;;
  *) echo "WARNING: could not parse verdict; read $OUT and treat as REVISE" >&2; exit 20 ;;
esac
